name: "Heroku Docker Web App Deployment"
author: "Elay Gelbart"
description: "Heroku Docker Web App Deployment"
inputs:
  herokuAppName:
    description: "Name of the heroku application to which the build is to be sent."
    required: true
  herokuApiKey:
    description: "Heroku API key"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
