name: "Heroku Deployment"
author: "Elay Gelbart"
description: "Heroku Deployment"
inputs:
  herokuAppName:
    description: "Name of the heroku application to which the build is to be sent."
    required: true
  herokuApiKey:
    description: "Heroku API key"
    required: true
  deploymentWithGit:
    description: "Selected branch to deployment"
    default: "false"
    required: false
  branch:
    description: "Selected branch to deployment"
    default: "HEAD"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
