name: Deploy To Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i
      - run: npm run build
      - run: cd ../server
      - run: npm i
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "reactchatforumapp"
          heroku_email: "elaygelbart@gmail.com"
          justlogin: true

      - name: "Login to heroku registry"
      - run: heroku container:login

      - name: "Build and push to heroku registry"
      - run: heroku container:push web --app email-service-web

      - name: "Releases the container"
      - run: heroku container:release web --app email-service-web
