name: Deploy To Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i
      - run: npm run build
      - run: cd ..
      - run: git pull heroku
      - run: cd server
      - run: npm i
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "reactchatforumapp"
          heroku_email: "elaygelbart@gmail.com"
